#  AtomMiner am01_pinout.xdc example 
#  Copyright 2016-2020 AtomMiner <atom@atomminer.com>
 
 
# This code is free software; you can redistribute it and/or modify it
# under the terms of the BSD 3-Clause License as published by the Free
# Software Foundation; See COPYING for more details.
 
# This provides refernce pin assignments. Must be changed according to real project need.
# Please refer to AM01 FPGA schematic for more details.


set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {DQ[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DQ[0]}]
set_property SLEW FAST [get_ports {DQ[31]}]
set_property SLEW FAST [get_ports {DQ[30]}]
set_property SLEW FAST [get_ports {DQ[29]}]
set_property SLEW FAST [get_ports {DQ[28]}]
set_property SLEW FAST [get_ports {DQ[27]}]
set_property SLEW FAST [get_ports {DQ[26]}]
set_property SLEW FAST [get_ports {DQ[25]}]
set_property SLEW FAST [get_ports {DQ[24]}]
set_property SLEW FAST [get_ports {DQ[23]}]
set_property SLEW FAST [get_ports {DQ[22]}]
set_property SLEW FAST [get_ports {DQ[21]}]
set_property SLEW FAST [get_ports {DQ[20]}]
set_property SLEW FAST [get_ports {DQ[19]}]
set_property SLEW FAST [get_ports {DQ[18]}]
set_property SLEW FAST [get_ports {DQ[17]}]
set_property SLEW FAST [get_ports {DQ[16]}]
set_property SLEW FAST [get_ports {DQ[15]}]
set_property SLEW FAST [get_ports {DQ[14]}]
set_property SLEW FAST [get_ports {DQ[13]}]
set_property SLEW FAST [get_ports {DQ[12]}]
set_property SLEW FAST [get_ports {DQ[11]}]
set_property SLEW FAST [get_ports {DQ[10]}]
set_property SLEW FAST [get_ports {DQ[9]}]
set_property SLEW FAST [get_ports {DQ[8]}]
set_property SLEW FAST [get_ports {DQ[7]}]
set_property SLEW FAST [get_ports {DQ[6]}]
set_property SLEW FAST [get_ports {DQ[5]}]
set_property SLEW FAST [get_ports {DQ[4]}]
set_property SLEW FAST [get_ports {DQ[3]}]
set_property SLEW FAST [get_ports {DQ[2]}]
set_property SLEW FAST [get_ports {DQ[1]}]
set_property SLEW FAST [get_ports {DQ[0]}]

set_property PACKAGE_PIN H17 [get_ports hash_is_go]
set_property IOSTANDARD LVCMOS33 [get_ports hash_is_go]

set_property PACKAGE_PIN W19 [get_ports pclk]
set_property IOSTANDARD LVCMOS33 [get_ports pclk]

set_property PACKAGE_PIN AA19 [get_ports we]
set_property IOSTANDARD LVCMOS33 [get_ports we]

set_property PACKAGE_PIN J19 [get_ports artix_ready]
set_property IOSTANDARD LVCMOS33 [get_ports artix_ready]
set_property PACKAGE_PIN J20 [get_ports FX3_ready]
set_property IOSTANDARD LVCMOS33 [get_ports FX3_ready]
set_property PACKAGE_PIN K18 [get_ports gclk]
set_property IOSTANDARD LVCMOS33 [get_ports gclk]
set_property PACKAGE_PIN W20 [get_ports strobe_data]
set_property IOSTANDARD LVCMOS33 [get_ports strobe_data]
set_property PACKAGE_PIN M20 [get_ports sec_key]
set_property IOSTANDARD LVCMOS33 [get_ports sec_key]
set_property PACKAGE_PIN M18 [get_ports FX3_comm]
set_property IOSTANDARD LVCMOS33 [get_ports FX3_comm]


set_property PACKAGE_PIN W17 [get_ports {DQ[31]}]
set_property PACKAGE_PIN AA18 [get_ports {DQ[30]}]
set_property PACKAGE_PIN AB18 [get_ports {DQ[29]}]
set_property PACKAGE_PIN U17 [get_ports {DQ[28]}]
set_property PACKAGE_PIN U18 [get_ports {DQ[27]}]
set_property PACKAGE_PIN P14 [get_ports {DQ[26]}]
set_property PACKAGE_PIN R14 [get_ports {DQ[25]}]
set_property PACKAGE_PIN R18 [get_ports {DQ[24]}]
set_property PACKAGE_PIN T18 [get_ports {DQ[23]}]
set_property PACKAGE_PIN P17 [get_ports {DQ[22]}]
set_property PACKAGE_PIN P15 [get_ports {DQ[21]}]
set_property PACKAGE_PIN R16 [get_ports {DQ[20]}]
set_property PACKAGE_PIN N13 [get_ports {DQ[19]}]
set_property PACKAGE_PIN N14 [get_ports {DQ[18]}]
set_property PACKAGE_PIN P16 [get_ports {DQ[17]}]
set_property PACKAGE_PIN R17 [get_ports {DQ[16]}]
set_property PACKAGE_PIN AB22 [get_ports {DQ[15]}]
set_property PACKAGE_PIN AB21 [get_ports {DQ[14]}]
set_property PACKAGE_PIN Y22 [get_ports {DQ[13]}]
set_property PACKAGE_PIN AA21 [get_ports {DQ[12]}]
set_property PACKAGE_PIN AA20 [get_ports {DQ[11]}]
set_property PACKAGE_PIN W22 [get_ports {DQ[10]}]
set_property PACKAGE_PIN W21 [get_ports {DQ[9]}]
set_property PACKAGE_PIN T20 [get_ports {DQ[8]}]
set_property PACKAGE_PIN R19 [get_ports {DQ[7]}]
set_property PACKAGE_PIN P19 [get_ports {DQ[6]}]
set_property PACKAGE_PIN U21 [get_ports {DQ[5]}]
set_property PACKAGE_PIN T21 [get_ports {DQ[4]}]
set_property PACKAGE_PIN R21 [get_ports {DQ[3]}]
set_property PACKAGE_PIN P21 [get_ports {DQ[2]}]
set_property PACKAGE_PIN R22 [get_ports {DQ[1]}]
set_property PACKAGE_PIN P22 [get_ports {DQ[0]}]
